variables:
  GITHUB_USER: $GITHUB_USERNAME
  GITHUB_PASS: $GITHUB_PASSWORD

stages:
  - deploy

Git MIRROR:
  stage: deploy
  script:
    - git push --mirror https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME.git