variables:
  GITHUB_USER: $GITHUB_USERNAME
  GITHUB_PASS: $GITHUB_PASSWORD

stages:
  - deploy

Git MIRROR:
  stage: deploy
  script:
    - echo -e "Project Name $CI_PROJECT_NAME\nProject Namespace $CI_PROJECT_NAMESPACE\nProject Path $CI_PROJECT_PATH\nRegistry Image $CI_REGISTRY_IMAGE\nCommit Ref Name $CI_COMMIT_REF_NAME\n"
    - echo -e "Commit Tag - $CI_COMMIT_TAG\nCommit SHA - $CI_COMMIT_SHA\n"
    - git push --mirror https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME.git